#ifndef _SENSOR_TYPE_H_
#define _SENSOR_TYPE_H_
#define TYPE_ACCELEROMETER 					1
#define TYPE_MAGNETIC_FIELD 				2
#define TYPE_ORIENTATION 					3
#define TYPE_GYROSCOPE						4
#define TYPE_LIGHT							5
#define TYPE_PRESSURE						6
#define TYPE_TEMPERATURE 					7
#define TYPE_PROXIMITY						8
#define TYPE_GRAVITY						9
#define TYPE_LINEAR_ACCELERATION			10
#define TYPE_ROTATION_VECTOR 				11
#define TYPE_RELATIVE_HUMIDITY 				12
#define TYPE_AMBIENT_TEMPERATURE 			13
#define TYPE_MAGNETIC_FIELD_UNCALIBRATED 	14
#define TYPE_GAME_ROTATION_VECTOR 			15
#define TYPE_GYROSCOPE_UNCALIBRATED			16
#define TYPE_SIGNIFICANT_MOTION 			17
#define TYPE_STEP_DETECTOR 					18
#define TYPE_STEP_COUNTER 					19
#define TYPE_GEOMAGNETIC_ROTATION_VECTOR 	20
#define TYPE_HEART_RATE 					21
#define TYPE_TILT_DETECTOR 					22
#define TYPE_WAKE_GESTURE 					23
#define TYPE_GLANCE_GESTURE 				24
#define TYPE_PICK_UP_GESTURE 				25
#define TYPE_WRIST_TILT_GESTURE 			26
#define TYPE_DEVICE_ORIENTATION				27
#define TYPE_POSE_6DOF						28
#define TYPE_STATIONARY_DETECT 				29
#define TYPE_MOTION_DETECT 					30
#define TYPE_HEART_BEAT 					31
#define TYPE_DYNAMIC_SENSOR_META			32
#define TYPE_LOW_LATENCY_OFFBODY_DETECT 	34
#define TYPE_ACCELEROMETER_UNCALIBRATED		35
#define TYPE_HINGE_ANGLE 					36
#define TYPE_ALL							-1

#define BAD_VALUE      -1
#define NO_ERROR        0

typedef  int status_t;
#endif
